In [42]:
import numpy as np 

In [43]:
L = [1, 2, 3]

A = np.array([1, 2, 3])

In [44]:
for l in L:
    print(l)

1
2
3


In [45]:
for l in A :
    print(l)

1
2
3


In [46]:
L.append(4)
L

[1, 2, 3, 4]

In [47]:
# A.append(4)
# A

In [48]:
L + [5]

[1, 2, 3, 4, 5]

In [49]:
A + np.array([5])

array([6, 7, 8])

In [50]:
A + np.array([4,5,6])

array([5, 7, 9])

In [51]:
# A + np.array([1,2])

In [52]:
2*A

array([2, 4, 6])

In [53]:
2*L

[1, 2, 3, 4, 1, 2, 3, 4]

In [54]:
L + L 

[1, 2, 3, 4, 1, 2, 3, 4]

In [55]:
A**2

array([1, 4, 9], dtype=int32)

In [56]:
np.sqrt(A)

array([1.        , 1.41421356, 1.73205081])

In [57]:
np.log(A)

array([0.        , 0.69314718, 1.09861229])

In [58]:
np.exp(A)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [59]:
np.tanh(A)

array([0.76159416, 0.96402758, 0.99505475])

In [60]:
np.sin(A)

array([0.84147098, 0.90929743, 0.14112001])

In [61]:
np.sin(90)

0.8939966636005579

In [62]:
np.sin(180)

-0.8011526357338304

In [118]:
a = np.array([1, 2])
b = np.array([3, 4])

In [105]:
dot = 0
dot

0

In [106]:
a*b

array([3, 8])

In [107]:
np.sum(a*b)

11

In [108]:
np.dot(a,b)

11

In [109]:
(a*b).sum()

11

In [110]:
a.dot(b)

11

In [112]:
a@b

11

In [120]:
amag = np.sqrt((a*a).sum())
amag

2.23606797749979

In [121]:
np.linalg.norm(a)

2.23606797749979

In [130]:
cosangle = a.dot(b)/(np.linalg.norm(a)*np.linalg.norm(b))
cosangle

0.9838699100999074

In [131]:
angle = np.arccos(cosangle)
angle

0.17985349979247847