In [7]:
import numpy as np 

In [8]:
A = np.array([[1,2],[3,4]])
A

array([[1, 2],
       [3, 4]])

In [9]:
A[0][1]

2

In [10]:
A[0,1]

2

In [12]:
A[:,0]

array([1, 3])

In [13]:
A.T

array([[1, 3],
       [2, 4]])

In [14]:
np.exp(A)

array([[ 2.71828183,  7.3890561 ],
       [20.08553692, 54.59815003]])

In [15]:
B= np.array([[1,2,3],[4,5,6]])
B

array([[1, 2, 3],
       [4, 5, 6]])

In [23]:
A.dot(B)

array([[ 9, 12, 15],
       [19, 26, 33]])

In [20]:
(B.T).dot(A.T)

array([[ 9, 19],
       [12, 26],
       [15, 33]])

In [24]:
np.linalg.det(A)

-2.0000000000000004

In [25]:
np.linalg.inv(A)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [26]:
np.linalg.inv(A).dot(A)

array([[1.00000000e+00, 0.00000000e+00],
       [1.11022302e-16, 1.00000000e+00]])

In [27]:
np.trace(A)

5

In [28]:
np.diag(A)

array([1, 4])

In [29]:
np.diag([1,4])

array([[1, 0],
       [0, 4]])

In [31]:
np.linalg.eig(A)    

(array([-0.37228132,  5.37228132]),
 array([[-0.82456484, -0.41597356],
        [ 0.56576746, -0.90937671]]))

In [32]:
C = np.array([[-6, 3],[4,5]])
C

array([[-6,  3],
       [ 4,  5]])

In [33]:
np.linalg.eig(C)

(array([-7.,  6.]),
 array([[-0.9486833 , -0.24253563],
        [ 0.31622777, -0.9701425 ]]))

In [35]:
np.linalg.eigvals(C)

array([-7.,  6.])

In [36]:
val , vec = np.linalg.eig(C)


In [48]:
vec[:,0]*val[0]     

array([ 6.64078309, -2.21359436])

In [49]:
C @vec[:,0]

array([ 6.64078309, -2.21359436])

In [50]:
vec[:,0]*val[0]      == C @vec[:,0]

array([ True, False])

In [52]:
np.allclose(vec[:,0]*val[0] ,C @vec[:,0])

True

In [56]:
np.allclose(vec@np.diag(val),C@vec)

True

In [58]:
A = np.array([[1,1],[1.5 ,4]])
B = np.array([[2200],[5050]])

In [61]:
np.linalg.inv(A)@B

array([[1500.],
       [ 700.]])

In [62]:
np.linalg.solve(A,B)

array([[1500.],
       [ 700.]])

In [85]:
R = np.random.randn(1000000,5)
R.mean()

-0.0004644950232263598

In [66]:
R.var()

1.0013106696715628

In [67]:
R.std()

1.000655120244514

In [83]:
np.random.randint(3)

2

In [87]:
np.mean(R,axis=0)

array([ 0.00174308, -0.00050628, -0.00064822, -0.00142566, -0.0014854 ])

In [90]:
np.mean(R,axis=1)


array([-0.07155507, -0.10629632, -0.10540251, ..., -0.22007794,
       -0.32568554,  0.02912003])